### ISSUE TITLE
General Question

### ISSUE THREAD

**Issue by anonymouz4** [AlessandroZ/LaZagneForensic#13]
@AlessandroZ 
Do you think it is a good idea if I include a `memory dump` (only `lsass`) in the `dump.ps1` file?

So people that run it as system could automatically decrypt the files of the current logged in users.

As an example [this short script](https://github.com/PowerShellMafia/PowerSploit/blob/master/Exfiltration/Out-Minidump.ps1) would be perfectly small, lightweight and av-undetectable, that could automatically create a mem_dump file without any dependencies.

**Comment by AlessandroZ** [comment]
Yes sure you can do it, just let the dump.ps1 like that and create a new file called "dump_with_lsass.ps1" (or whatever) with all applications and the memory dump. :+1:
