### ISSUE TITLE
HASHES instead of plaintext passwords?

### ISSUE THREAD

**Issue by anonymouz4** [AlessandroZ/LaZagneForensic#9]
Is it possible to use the hashes instead of needing the plaintext password to decrypt the dumped passwords?

In the script I've found the `-pwdhash` argument, it says:

> Windows user hash (not NTLM hash)

So which hash type does it require?

**Comment by AlessandroZ** [comment]
On some windows versions, you cannot retrieve the windows password in memory but you can get the sha1 hash. This hash is a derived hash from the cleartext user password. 
You can dump it from memory using lazagne (not lazagnefensic) or mimikatz.

For example, here is a mimikatz output that I've just taken from a blog: 
```
Authentication Id : 0 ; 646260 (00000000:0009dc74)
 Session           : RemoteInteractive from 2
 User Name         : adsadministrator
 Domain            : ADSECLAB
 Logon Server      : ADSDC03
 Logon Time        : 11/27/2015 11:41:27 AM
 SID               : S-1-5-21-1581655573-3923512380-696647894-500
 msv :
 [00000003] Primary
 * Username : ADSAdministrator
 * Domain   : ADSECLAB
 * NTLM     : 5164b7a0fda365d56739954bbbc23835
 * SHA1     : f8db297cb2ae403f8915675cebe79643d0d3b09f
 [00010000] CredentialKeys
 * NTLM     : 5164b7a0fda365d56739954bbbc23835
 * SHA1     : f8db297cb2ae403f8915675cebe79643d0d3b09f
 tspkg :
 wdigest :
 * Username : ADSAdministrator
 * Domain   : ADSECLAB
 * Password : (null)
 kerberos :
 * Username : adsadministrator
 * Domain   : LAB.ADSECURITY.ORG
 * Password : (null)
 ssp :   KO
```
You can see the sha1 on the ouput. This hash can be used to decrypt other passwords stored on the filesystem (with `-pwdhash`)

**Comment by anonymouz4** [comment]
only problem with tools like mimikatz and lazagne is that it will always get detected by almost any av instantly.
But Thanks for the answer :)
